[package]
name = "student_dapp_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
candid = "0.10"

# Use the latest stable compatible versions
ic-cdk = "0.18"
ic-cdk-macros = "0.18"

thiserror = "1.0"
